name: reserve
favicon: null
layout_spectrum: 1
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#d6e05d'
    - '#808080'
    - '#ffa63e'
    - '#c4bf2f'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
