name: reserve
favicon: null
layout_spectrum: 0
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a79386'
    - '#e6e2db'
    - '#79644f'
    - '#341e06'
    - '#07060b'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.03191081923432648
purpose: []
